### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by marketvision23** [bhays/gravity-forms-highrise-crm#3]
Not really sure why this is appearing, hoping someone can help out:

Fatal error: Call to undefined method HighriseAPI::testAccount() in /home/arcticfr/public_html/wp-content/plugins/gravity-forms-highrise/highrise.php on line 232

**Comment by bhays** [comment]
I believe you've got the wrong plugin, you're looking for one of the following: http://wordpress.org/plugins/gravity-forms-highrise/ or https://github.com/katzwebservices/Gravity-Forms-Highrise-Addon
