### ISSUE TITLE
If a user enters a '&' character, the plugin doesn't send the data to highrise

### ISSUE THREAD

**Issue by gregblass** [bhays/gravity-forms-highrise-crm#4]
It looks like the plugin is failing to send the entry to gravity forms if the user enters an "&" symbol into the job title field that we have. In our case, the user entered: "Client & Corporate Development" - and it doesn't go through because of the &.

**Comment by bhays** [comment]
Thanks for the heads up. The ampersand wasn't being escaped, and the Highrise API didn't like it hanging out in the XML. 

Just checked in a new version to GitHub and update via WordPress plugin repo is coming shortly.

**Comment by gregblass** [comment]
Your fix that you checked in is causing my site to give a PHP (5.4) error: 

Parse error: syntax error, unexpected T_FUNCTION plugins/gravity-forms-highrise-crm/gravity-forms-highrise-crm.php on line 1225.

// Get strings ready for XML
line 1225 ----> array_walk_recursive($params, function (&$value) {
$value = htmlentities($value, ENT_QUOTES, 'UTF-8');
});

**Comment by bhays** [comment]
Are you certain you're running PHP 5.4? 

The error you posted is due to the anonymous function within array_walk_recursive. PHP 5.3 and up should not have any issues with anonymous functions.
