### ISSUE TITLE
Possible to map LinkiedIn field to Highrise?

### ISSUE THREAD

**Issue by TPH31** [bhays/gravity-forms-highrise-crm#6]
Hello.

Is there a way to add a field to a form and map it to the LinkedIn field in Highrise?

many thanks.
-Tom

**Comment by bhays** [comment]
Hi Tom,

At this time there is no direct way to map directly to the LinkedIn field. One current solution would be to use a custom field that you created and save the data there, then moving it over in Highrise later.

Alternatively, I'm open to accepting a pull request if you would like to add the LinkedIn field yourself.
