### ISSUE TITLE
Unable to save Highrise CRM Feeds

### ISSUE THREAD

**Issue by zlorenz** [bhays/gravity-forms-highrise-crm#7]
@bhays 
I'm having an issue with saving Highrise CRM Feeds ever since I created a new WordPress Multisite for one of my clients. The issue is very similar to the [Not able to create feeds](https://wordpress.org/support/topic/not-able-to-create-feeds) support ticket.

Whenever I save a new feed, the "Feed Updated" alert pops-up but when I return to the list, there are no existing feeds. This is happening on both the primary website and the alternate site that I created with WP Multisite.

As you recommended in that support ticket, I checked the database tables within Bluehost but it looks like the correct table was indeed added (see screenshot below):
![screen shot 2015-04-24 at 2 47 20 pm](https://cloud.githubusercontent.com/assets/5069194/7329119/d73a8c78-ea90-11e4-8717-b999be396a83.png)

While troubleshooting, I also turned off all plugins except for Gravity Forms and Gravity Forms Highrise CRM but the problem continued to persist. Could this have something to do with the WP Multisite database that I've setup?

For your reference, my client's site is running these versions:
- **WordPress 4.2**
- **Gravity Forms 1.9.6**
- **Gravity Forms Highrise CRM 2.3**

**Comment by bhays** [comment]
Using the same versions, I was able to successfully create a Highrise feed. I thought the Multisite tables may have been the issue, but they are working okay for me.

Have you tried creating a Highrise feed with a different form? Also, if you can, send me the XML export for the form you're trying to create a feed for and I'll have a look.

**Comment by zlorenz** [comment]
@bhays Yes, I've tried creating feeds for at least 3 existing Gravity Forms.

It looks like Gravity Forms 1.9 no longer supports XML. I was only given the option to export the forms as JSON objects. Here they are:

[test-form.json | uploaded via ZenHub](https://files.zenhub.io/553c351a212daed03d483f3e)

[contact-form.json | uploaded via ZenHub](https://files.zenhub.io/553c351a212daed03d483f3f)

[employment-application.json | uploaded via ZenHub](https://files.zenhub.io/553c351b212daed03d483f40)

**Comment by zlorenz** [comment]
@bhays 
Any updates on this? I know this must be a pain...but my client desperately needs to figure this out, otherwise she will probably have to switch to a new CRM entirely as there are no other Highrise/Gravity Form integration plugins.

Just let me know as soon as possible. Thanks!

**Comment by bhays** [comment]
I was able to try your other test forms, but still haven't been able to re-create the issue. The form feeds are all adding to the database for me.

Have you tried the WordPress Debug plugin to see if there are any errors from the database when the record is being created? Are there any installed plugins that may be monitoring the database or limiting inserts somehow?

**Comment by bhays** [comment]
Closing this for now, I'll assume you got things working unless I hear otherwise.
